name: ci/gh-actions/gitian

on: [push]

jobs:
  build-gitian:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - name: "Linux"
            option: "l"
          - name: "Windows"
            option: "w"
          - name: "Android"
            option: "a"
          - name: "FreeBSD"
            option: "f"
          - name: "macOS"
            option: "m"
    name: ${{ matrix.operating-system.name }}
    steps:
    - name: build
      run: |
        id
        curl -O https://raw.githubusercontent.com/monero-project/monero/v0.18.1.2/contrib/gitian/gitian-build.py
        chmod +x gitian-build.py
        ./gitian-build.py --setup --docker github-actions v0.18.1.2
        ./gitian-build.py --docker --detach-sign --no-commit --build -j 3 -o ${{ matrix.operating-system.option }} github-actions v0.18.1.2
    - name: post build
      run: |
        shasum -a256 out/v0.18.1.2/*
        echo \`\`\` >> $GITHUB_STEP_SUMMARY
        shasum -a256 out/v0.18.1.2/* >> $GITHUB_STEP_SUMMARY
        echo \`\`\` >> $GITHUB_STEP_SUMMARY
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ matrix.operating-system.name }}
        path: |
          out/v0.18.1.2/*
